// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cookie": {
            "put": {
                "description": "保存COOKIE",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COOKIE"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization BACKEND_SECRET",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "COOKIE信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CookieSaveReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/cookie/all": {
            "get": {
                "description": "查询全量COOKIE",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COOKIE"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization BACKEND_SECRET",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.ResponseResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.CookieResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/cookie/credit/refresh": {
            "post": {
                "description": "同步更新全量COOKIE额度",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COOKIE"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization BACKEND_SECRET",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/cookie/update": {
            "post": {
                "description": "更新COOKIE",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COOKIE"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization BACKEND_SECRET",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "COOKIE信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CookieUpdateReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/cookie/{id}": {
            "delete": {
                "description": "删除COOKIE",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COOKIE"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization BACKEND_SECRET",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "COOKIE ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/key": {
            "put": {
                "description": "保存API-KEY",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API-KEY"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization BACKEND_SECRET",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "API-KEY信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ApiKeySaveReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/key/all": {
            "get": {
                "description": "查询全量API-KEY",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API-KEY"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization BACKEND_SECRET",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.ResponseResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.ApiKeyResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/key/update": {
            "post": {
                "description": "更新API-KEY",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API-KEY"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization BACKEND_SECRET",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "API-KEY信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ApiKeyUpdateReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/key/{id}": {
            "delete": {
                "description": "删除API-KEY",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API-KEY"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization BACKEND_SECRET",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API-KEY ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/chat/completions": {
            "post": {
                "description": "OpenAI对话接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OpenAI"
                ],
                "parameters": [
                    {
                        "description": "OpenAI对话请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OpenAIChatCompletionRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization API-KEY",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/models": {
            "get": {
                "description": "OpenAI模型列表接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OpenAI"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization API-KEY",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.ResponseResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.OpenaiModelListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.ResponseResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "model.ApiKeyResp": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "description": "ApiKey apiKey",
                    "type": "string"
                },
                "createTime": {
                    "description": "CreateTime 创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "Id Id",
                    "type": "string"
                },
                "remark": {
                    "description": "Remark 备注",
                    "type": "string"
                }
            }
        },
        "model.ApiKeySaveReq": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "description": "ApiKey apiKey",
                    "type": "string"
                },
                "remark": {
                    "description": "Remark 备注",
                    "type": "string"
                }
            }
        },
        "model.ApiKeyUpdateReq": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "description": "ApiKey apiKey",
                    "type": "string"
                },
                "id": {
                    "description": "Id id",
                    "type": "string"
                },
                "remark": {
                    "description": "Remark 备注",
                    "type": "string"
                }
            }
        },
        "model.CookieResp": {
            "type": "object",
            "properties": {
                "cookie": {
                    "description": "Cookie cookie",
                    "type": "string"
                },
                "createTime": {
                    "description": "CreateTime 创建时间",
                    "type": "string"
                },
                "credit": {
                    "description": "Credit 额度",
                    "type": "integer"
                },
                "id": {
                    "description": "Id Id",
                    "type": "string"
                },
                "remark": {
                    "description": "Remark 备注",
                    "type": "string"
                }
            }
        },
        "model.CookieSaveReq": {
            "type": "object",
            "properties": {
                "cookie": {
                    "description": "Cookie cookie",
                    "type": "string"
                },
                "remark": {
                    "description": "Remark 备注",
                    "type": "string"
                }
            }
        },
        "model.CookieUpdateReq": {
            "type": "object",
            "properties": {
                "cookie": {
                    "description": "Cookie cookie",
                    "type": "string"
                },
                "id": {
                    "description": "Id Id",
                    "type": "string"
                },
                "remark": {
                    "description": "Remark 备注",
                    "type": "string"
                }
            }
        },
        "model.OpenAIChatCompletionRequest": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OpenAIChatMessage"
                    }
                },
                "model": {
                    "type": "string"
                },
                "stream": {
                    "type": "boolean"
                }
            }
        },
        "model.OpenAIChatMessage": {
            "type": "object",
            "properties": {
                "content": {},
                "role": {
                    "type": "string"
                }
            }
        },
        "model.OpenaiModelListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OpenaiModelResponse"
                    }
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "model.OpenaiModelResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "HIX-AI-2API",
	Description:      "HIX-AI-2API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
